import { WeaponAttributes as A } from "../utilities/WeaponAttributes.js";

/**
 * WeaponDef shape (engine contract)
 * - id: string (stable key)
 * - name: string
 * - damage: number (base per pellet/hit)
 * - range: number (meters, hitscan falloff start)
 * - dropoff: number (0..1, how much damage is reduced at max range)
 * - ammoClip: number
 * - ammoMag: number (total reserve carried)
 * - rpm: number (rounds per minute)
 * - model: string (path to GLB or placeholder)
 * - attributes: string[] (tags / flags)
 * Optional:
 * - pellets: number (shotgun pellet count)
 * - spreadRad: number (radians) (shotgun spread)
 * - aoeRadius: number (meters) (explosive radius)
 * - aoeDamageMul: number (0..1) (explosion damage fraction)
 */
export const WeaponDefs = Object.freeze({
  // Pistols (8)
  glock_19: {
    id: "glock_19",
    name: "Glock 19",
    damage: 22,
    range: 28,
    dropoff: 0.35,
    ammoClip: 15,
    ammoMag: 90,
    rpm: 420,
    model: "/engine/core/weapons/assets/glock19.glb",
    attributes: [A.Pistol, A.SemiAuto],
  },
  p_1911: {
    id: "p_1911",
    name: "M1911",
    damage: 28,
    range: 24,
    dropoff: 0.40,
    ammoClip: 8,
    ammoMag: 72,
    rpm: 360,
    model: "/engine/core/weapons/assets/1911.glb",
    attributes: [A.Pistol, A.SemiAuto],
  },
  p_m9: {
    id: "p_m9",
    name: "M9",
    damage: 21,
    range: 26,
    dropoff: 0.35,
    ammoClip: 15,
    ammoMag: 105,
    rpm: 420,
    model: "/engine/core/weapons/assets/m9.glb",
    attributes: [A.Pistol, A.SemiAuto],
  },
  p_usp: {
    id: "p_usp",
    name: "USP .45",
    damage: 26,
    range: 26,
    dropoff: 0.35,
    ammoClip: 12,
    ammoMag: 96,
    rpm: 400,
    model: "/engine/core/weapons/assets/usp45.glb",
    attributes: [A.Pistol, A.SemiAuto],
  },
  p_fn57: {
    id: "p_fn57",
    name: "FN Five-seveN",
    damage: 19,
    range: 30,
    dropoff: 0.30,
    ammoClip: 20,
    ammoMag: 140,
    rpm: 460,
    model: "/engine/core/weapons/assets/fn57.glb",
    attributes: [A.Pistol, A.SemiAuto],
  },
  p_revolver: {
    id: "p_revolver",
    name: "Revolver",
    damage: 40,
    range: 32,
    dropoff: 0.30,
    ammoClip: 6,
    ammoMag: 48,
    rpm: 180,
    model: "/engine/core/weapons/assets/revolver.glb",
    attributes: [A.Pistol, A.SemiAuto],
  },
  p_deagle: {
    id: "p_deagle",
    name: "Desert Eagle",
    damage: 52,
    range: 34,
    dropoff: 0.28,
    ammoClip: 7,
    ammoMag: 56,
    rpm: 220,
    model: "/engine/core/weapons/assets/deagle.glb",
    attributes: [A.Pistol, A.SemiAuto],
  },
  p_g18_auto: {
    id: "p_g18_auto",
    name: "G18 (Auto)",
    damage: 16,
    range: 22,
    dropoff: 0.45,
    ammoClip: 18,
    ammoMag: 144,
    rpm: 900,
    model: "/engine/core/weapons/assets/g18.glb",
    attributes: [A.Pistol, A.FullAuto, A.SMG],
  },

  // Assault Rifles (8)
  ar_m4: {
    id: "ar_m4",
    name: "M4A1",
    damage: 24,
    range: 55,
    dropoff: 0.25,
    ammoClip: 30,
    ammoMag: 210,
    rpm: 750,
    model: "/engine/core/weapons/assets/m4a1.glb",
    attributes: [A.Rifle, A.FullAuto],
  },
  ar_ak47: {
    id: "ar_ak47",
    name: "AK-47",
    damage: 30,
    range: 52,
    dropoff: 0.28,
    ammoClip: 30,
    ammoMag: 180,
    rpm: 600,
    model: "/engine/core/weapons/assets/ak47.glb",
    attributes: [A.Rifle, A.FullAuto],
  },
  ar_g36c: {
    id: "ar_g36c",
    name: "G36C",
    damage: 23,
    range: 54,
    dropoff: 0.25,
    ammoClip: 30,
    ammoMag: 210,
    rpm: 780,
    model: "/engine/core/weapons/assets/g36c.glb",
    attributes: [A.Rifle, A.FullAuto],
  },
  ar_scarh: {
    id: "ar_scarh",
    name: "SCAR-H",
    damage: 33,
    range: 58,
    dropoff: 0.22,
    ammoClip: 20,
    ammoMag: 160,
    rpm: 560,
    model: "/engine/core/weapons/assets/scarh.glb",
    attributes: [A.Rifle, A.FullAuto],
  },
  ar_an94: {
    id: "ar_an94",
    name: "AN-94",
    damage: 25,
    range: 56,
    dropoff: 0.24,
    ammoClip: 30,
    ammoMag: 210,
    rpm: 720,
    model: "/engine/core/weapons/assets/an94.glb",
    attributes: [A.Rifle, A.FullAuto],
  },
  ar_aug: {
    id: "ar_aug",
    name: "AUG A3",
    damage: 24,
    range: 55,
    dropoff: 0.25,
    ammoClip: 30,
    ammoMag: 210,
    rpm: 680,
    model: "/engine/core/weapons/assets/aug.glb",
    attributes: [A.Rifle, A.FullAuto],
  },
  ar_m16_burst: {
    id: "ar_m16_burst",
    name: "M16A4 (Burst)",
    damage: 27,
    range: 60,
    dropoff: 0.20,
    ammoClip: 30,
    ammoMag: 180,
    rpm: 900,
    model: "/engine/core/weapons/assets/m16.glb",
    attributes: [A.Rifle, A.BurstFire],
  },
  ar_famas_burst: {
    id: "ar_famas_burst",
    name: "FAMAS (Burst)",
    damage: 26,
    range: 52,
    dropoff: 0.25,
    ammoClip: 30,
    ammoMag: 180,
    rpm: 900,
    model: "/engine/core/weapons/assets/famas.glb",
    attributes: [A.Rifle, A.BurstFire],
  },

  // Sub Machine Guns (8)
  smg_mp5: {
    id: "smg_mp5",
    name: "MP5",
    damage: 19,
    range: 32,
    dropoff: 0.40,
    ammoClip: 30,
    ammoMag: 240,
    rpm: 800,
    model: "/engine/core/weapons/assets/mp5.glb",
    attributes: [A.SMG, A.FullAuto],
  },
  smg_ump45: {
    id: "smg_ump45",
    name: "UMP45",
    damage: 23,
    range: 34,
    dropoff: 0.38,
    ammoClip: 25,
    ammoMag: 200,
    rpm: 650,
    model: "/engine/core/weapons/assets/ump45.glb",
    attributes: [A.SMG, A.FullAuto],
  },
  smg_vector: {
    id: "smg_vector",
    name: "KRISS Vector",
    damage: 18,
    range: 30,
    dropoff: 0.42,
    ammoClip: 25,
    ammoMag: 225,
    rpm: 1100,
    model: "/engine/core/weapons/assets/vector.glb",
    attributes: [A.SMG, A.FullAuto],
  },
  smg_p90: {
    id: "smg_p90",
    name: "P90",
    damage: 17,
    range: 34,
    dropoff: 0.40,
    ammoClip: 50,
    ammoMag: 250,
    rpm: 900,
    model: "/engine/core/weapons/assets/p90.glb",
    attributes: [A.SMG, A.FullAuto],
  },
  smg_mp7: {
    id: "smg_mp7",
    name: "MP7",
    damage: 18,
    range: 32,
    dropoff: 0.40,
    ammoClip: 40,
    ammoMag: 240,
    rpm: 950,
    model: "/engine/core/weapons/assets/mp7.glb",
    attributes: [A.SMG, A.FullAuto],
  },
  smg_pp19: {
    id: "smg_pp19",
    name: "PP-19 Bizon",
    damage: 19,
    range: 33,
    dropoff: 0.40,
    ammoClip: 64,
    ammoMag: 256,
    rpm: 700,
    model: "/engine/core/weapons/assets/pp19.glb",
    attributes: [A.SMG, A.FullAuto],
  },
  smg_mac10: {
    id: "smg_mac10",
    name: "MAC-10",
    damage: 16,
    range: 26,
    dropoff: 0.50,
    ammoClip: 32,
    ammoMag: 224,
    rpm: 1050,
    model: "/engine/core/weapons/assets/mac10.glb",
    attributes: [A.SMG, A.FullAuto],
  },
  smg_sten: {
    id: "smg_sten",
    name: "STEN",
    damage: 20,
    range: 34,
    dropoff: 0.38,
    ammoClip: 32,
    ammoMag: 192,
    rpm: 540,
    model: "/engine/core/weapons/assets/sten.glb",
    attributes: [A.SMG, A.FullAuto],
  },

  // Light Machine Guns (7)
  lmg_mg42: {
    id: "lmg_mg42",
    name: "MG42",
    damage: 24,
    range: 60,
    dropoff: 0.22,
    ammoClip: 50,
    ammoMag: 250,
    rpm: 1200,
    model: "/engine/core/weapons/assets/mg42.glb",
    attributes: [A.LMG, A.FullAuto],
  },
  lmg_m249: {
    id: "lmg_m249",
    name: "M249 SAW",
    damage: 23,
    range: 58,
    dropoff: 0.22,
    ammoClip: 75,
    ammoMag: 300,
    rpm: 850,
    model: "/engine/core/weapons/assets/m249.glb",
    attributes: [A.LMG, A.FullAuto],
  },
  lmg_m60: {
    id: "lmg_m60",
    name: "M60",
    damage: 28,
    range: 62,
    dropoff: 0.20,
    ammoClip: 50,
    ammoMag: 250,
    rpm: 550,
    model: "/engine/core/weapons/assets/m60.glb",
    attributes: [A.LMG, A.FullAuto],
  },
  lmg_rpd: {
    id: "lmg_rpd",
    name: "RPD",
    damage: 26,
    range: 60,
    dropoff: 0.22,
    ammoClip: 75,
    ammoMag: 300,
    rpm: 650,
    model: "/engine/core/weapons/assets/rpd.glb",
    attributes: [A.LMG, A.FullAuto],
  },
  lmg_pkp: {
    id: "lmg_pkp",
    name: "PKP Pecheneg",
    damage: 27,
    range: 62,
    dropoff: 0.20,
    ammoClip: 100,
    ammoMag: 300,
    rpm: 700,
    model: "/engine/core/weapons/assets/pkp.glb",
    attributes: [A.LMG, A.FullAuto],
  },
  lmg_bren: {
    id: "lmg_bren",
    name: "Bren",
    damage: 25,
    range: 58,
    dropoff: 0.22,
    ammoClip: 30,
    ammoMag: 210,
    rpm: 500,
    model: "/engine/core/weapons/assets/bren.glb",
    attributes: [A.LMG, A.FullAuto],
  },
  lmg_stoner: {
    id: "lmg_stoner",
    name: "Stoner 63",
    damage: 22,
    range: 56,
    dropoff: 0.24,
    ammoClip: 75,
    ammoMag: 300,
    rpm: 800,
    model: "/engine/core/weapons/assets/stoner63.glb",
    attributes: [A.LMG, A.FullAuto],
  },

  // Shotguns (8) - damage tuned to ~40-70 per shot at close range via pellets
  sg_pump: {
    id: "sg_pump",
    name: "Pump Shotgun",
    damage: 8,
    pellets: 7,          // ~56 total at close range
    spreadRad: 0.065,
    range: 16,
    dropoff: 0.65,
    ammoClip: 6,
    ammoMag: 48,
    rpm: 70,
    model: "/engine/core/weapons/assets/pumpshotgun.glb",
    attributes: [A.Shotgun, A.SemiAuto],
  },
  sg_double: {
    id: "sg_double",
    name: "Double Barrel",
    damage: 10,
    pellets: 7,          // ~70
    spreadRad: 0.070,
    range: 14,
    dropoff: 0.68,
    ammoClip: 2,
    ammoMag: 30,
    rpm: 90,
    model: "/engine/core/weapons/assets/doublebarrel.glb",
    attributes: [A.Shotgun, A.SemiAuto],
  },
  sg_semi: {
    id: "sg_semi",
    name: "Semi Shotgun",
    damage: 7,
    pellets: 7,          // ~49
    spreadRad: 0.060,
    range: 17,
    dropoff: 0.62,
    ammoClip: 8,
    ammoMag: 56,
    rpm: 180,
    model: "/engine/core/weapons/assets/semishotgun.glb",
    attributes: [A.Shotgun, A.SemiAuto],
  },
  sg_spas12: {
    id: "sg_spas12",
    name: "SPAS-12",
    damage: 7,
    pellets: 7,          // ~49
    spreadRad: 0.060,
    range: 18,
    dropoff: 0.60,
    ammoClip: 8,
    ammoMag: 64,
    rpm: 200,
    model: "/engine/core/weapons/assets/spas12.glb",
    attributes: [A.Shotgun, A.SemiAuto],
  },
  sg_ksg: {
    id: "sg_ksg",
    name: "KSG",
    damage: 8,
    pellets: 6,          // ~48
    spreadRad: 0.055,
    range: 20,
    dropoff: 0.58,
    ammoClip: 12,
    ammoMag: 60,
    rpm: 120,
    model: "/engine/core/weapons/assets/ksg.glb",
    attributes: [A.Shotgun, A.SemiAuto],
  },
  sg_sawedoff: {
    id: "sg_sawedoff",
    name: "Sawed-Off",
    damage: 10,
    pellets: 6,          // ~60
    spreadRad: 0.085,
    range: 12,
    dropoff: 0.72,
    ammoClip: 2,
    ammoMag: 28,
    rpm: 110,
    model: "/engine/core/weapons/assets/sawedoff.glb",
    attributes: [A.Shotgun, A.SemiAuto],
  },
  sg_auto: {
    id: "sg_auto",
    name: "Street Sweeper (Auto)",
    damage: 6,
    pellets: 7,          // ~42
    spreadRad: 0.070,
    range: 16,
    dropoff: 0.66,
    ammoClip: 12,
    ammoMag: 72,
    rpm: 330,
    model: "/engine/core/weapons/assets/autoshotgun.glb",
    attributes: [A.Shotgun, A.FullAuto],
  },
  sg_aa12: {
    id: "sg_aa12",
    name: "AA-12",
    damage: 6,
    pellets: 7,          // ~42
    spreadRad: 0.065,
    range: 16,
    dropoff: 0.66,
    ammoClip: 20,
    ammoMag: 100,
    rpm: 420,
    model: "/engine/core/weapons/assets/aa12.glb",
    attributes: [A.Shotgun, A.FullAuto],
  },

  // Snipers (7)
  sn_mosin: {
    id: "sn_mosin",
    name: "Mosin-Nagant",
    damage: 90,
    range: 120,
    dropoff: 0.10,
    ammoClip: 5,
    ammoMag: 45,
    rpm: 55,
    model: "/engine/core/weapons/assets/mosin.glb",
    attributes: [A.Sniper, A.SemiAuto],
  },
  sn_m700: {
    id: "sn_m700",
    name: "M700",
    damage: 85,
    range: 120,
    dropoff: 0.10,
    ammoClip: 5,
    ammoMag: 40,
    rpm: 55,
    model: "/engine/core/weapons/assets/m700.glb",
    attributes: [A.Sniper, A.SemiAuto],
  },
  sn_kar98: {
    id: "sn_kar98",
    name: "Kar98k",
    damage: 88,
    range: 120,
    dropoff: 0.10,
    ammoClip: 5,
    ammoMag: 35,
    rpm: 55,
    model: "/engine/core/weapons/assets/kar98.glb",
    attributes: [A.Sniper, A.SemiAuto],
  },
  sn_l96: {
    id: "sn_l96",
    name: "L96A1",
    damage: 92,
    range: 130,
    dropoff: 0.10,
    ammoClip: 5,
    ammoMag: 35,
    rpm: 50,
    model: "/engine/core/weapons/assets/l96.glb",
    attributes: [A.Sniper, A.SemiAuto],
  },
  sn_svd: {
    id: "sn_svd",
    name: "Dragunov SVD",
    damage: 70,
    range: 110,
    dropoff: 0.12,
    ammoClip: 10,
    ammoMag: 60,
    rpm: 240,
    model: "/engine/core/weapons/assets/svd.glb",
    attributes: [A.Sniper, A.SemiAuto],
  },
  sn_barrett: {
    id: "sn_barrett",
    name: "Barrett .50",
    damage: 140,
    range: 150,
    dropoff: 0.08,
    ammoClip: 5,
    ammoMag: 25,
    rpm: 40,
    model: "/engine/core/weapons/assets/barrett.glb",
    attributes: [A.Sniper, A.SemiAuto],
  },
  sn_sks: {
    id: "sn_sks",
    name: "SKS",
    damage: 60,
    range: 90,
    dropoff: 0.15,
    ammoClip: 10,
    ammoMag: 100,
    rpm: 260,
    model: "/engine/core/weapons/assets/sks.glb",
    attributes: [A.Sniper, A.SemiAuto],
  },

  // Launchers (7) - use explosive AoE
  la_rpg7: {
    id: "la_rpg7",
    name: "RPG-7",
    damage: 120,
    range: 45,
    dropoff: 0.10,
    ammoClip: 1,
    ammoMag: 8,
    rpm: 45,
    aoeRadius: 4.5,
    aoeDamageMul: 0.75,
    model: "/engine/core/weapons/assets/rpg7.glb",
    attributes: [A.Launcher, A.ExplosiveRounds, A.SemiAuto],
  },
  la_m72: {
    id: "la_m72",
    name: "M72 LAW",
    damage: 110,
    range: 45,
    dropoff: 0.10,
    ammoClip: 1,
    ammoMag: 10,
    rpm: 55,
    aoeRadius: 4.0,
    aoeDamageMul: 0.70,
    model: "/engine/core/weapons/assets/m72.glb",
    attributes: [A.Launcher, A.ExplosiveRounds, A.SemiAuto],
  },
  la_panzer: {
    id: "la_panzer",
    name: "Panzerfaust",
    damage: 130,
    range: 40,
    dropoff: 0.10,
    ammoClip: 1,
    ammoMag: 6,
    rpm: 40,
    aoeRadius: 5.0,
    aoeDamageMul: 0.80,
    model: "/engine/core/weapons/assets/panzerfaust.glb",
    attributes: [A.Launcher, A.ExplosiveRounds, A.SemiAuto],
  },
  la_m79: {
    id: "la_m79",
    name: "M79 (Thumper)",
    damage: 95,
    range: 40,
    dropoff: 0.12,
    ammoClip: 1,
    ammoMag: 16,
    rpm: 70,
    aoeRadius: 3.5,
    aoeDamageMul: 0.65,
    model: "/engine/core/weapons/assets/m79.glb",
    attributes: [A.Launcher, A.ExplosiveRounds, A.SemiAuto],
  },
  la_gl: {
    id: "la_gl",
    name: "Grenade Launcher",
    damage: 85,
    range: 35,
    dropoff: 0.12,
    ammoClip: 6,
    ammoMag: 24,
    rpm: 140,
    aoeRadius: 3.2,
    aoeDamageMul: 0.60,
    model: "/engine/core/weapons/assets/grenadelauncher.glb",
    attributes: [A.Launcher, A.ExplosiveRounds, A.SemiAuto],
  },
  la_stinger: {
    id: "la_stinger",
    name: "Stinger",
    damage: 150,
    range: 55,
    dropoff: 0.08,
    ammoClip: 1,
    ammoMag: 4,
    rpm: 30,
    aoeRadius: 5.5,
    aoeDamageMul: 0.85,
    model: "/engine/core/weapons/assets/stinger.glb",
    attributes: [A.Launcher, A.ExplosiveRounds, A.SemiAuto],
  },
  la_bazooka: {
    id: "la_bazooka",
    name: "Bazooka",
    damage: 115,
    range: 45,
    dropoff: 0.10,
    ammoClip: 1,
    ammoMag: 7,
    rpm: 45,
    aoeRadius: 4.5,
    aoeDamageMul: 0.75,
    model: "/engine/core/weapons/assets/bazooka.glb",
    attributes: [A.Launcher, A.ExplosiveRounds, A.SemiAuto],
  },

  // Fun modifier examples
  ar_m4_explosive: {
    id: "ar_m4_explosive",
    name: "M4A1 (Explosive Rounds)",
    damage: 20,
    range: 45,
    dropoff: 0.20,
    ammoClip: 25,
    ammoMag: 125,
    rpm: 650,
    aoeRadius: 2.8,
    aoeDamageMul: 0.60,
    model: "/engine/core/weapons/assets/m4a1.glb",
    attributes: [A.Rifle, A.FullAuto, A.ExplosiveRounds],
  },
});
